#!/usr/bin/env bash
# booooooring

print_subs()
{
    DOM=$1
    SUB=$2
    if [ "$DOM" ] && [ "$SUB" ]
    then
	dig $SUB.$DOM | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:' | awk -v s="$SUB" '{print "The subdomain "s" is a "$4" record and points to "$5""}' 
    elif [ "$DOM" ]
    then
	for subs in www web-01 web-02 lb-01;
        do
	    dig $subs."$DOM" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:' | awk -v s="$subs" '{print "The subdomain "s" is a "$4" record and points \
to "$5""}'
	done
    fi
}
print_subs $1 $2
