#!/usr/bin/env bash
#bla bla bla hate this forever
#sudo apt-get update
#sudo apt-get -y install nginx
#echo 'holberton school' | sudo tee /var/www/html/index.html
#sudo service nginx start
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
