#!/usr/bin/env bash
#laaaazzzzy

sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sed -i "/http/ a\\http {\n\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/nginx.conf
service nginx restart
